<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_buku extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if (!$this->session->userdata("siswa_logged_in")) {
            redirect("siswa/Auth");
        }
        $this->load->model('T_buku_model');
    }

    public function index()
    {
        /*
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        */

        $judul_buku = urldecode($this->input->get('judul_buku', TRUE));
        $id_kategori = urldecode($this->input->get('id_kategori', TRUE));
        $id_rak = urldecode($this->input->get('id_rak', TRUE));
        $tahun = urldecode($this->input->get('tahun', TRUE));
        $start = intval($this->input->get('start'));

        $config['base_url'] = base_url() . 'siswa/t_buku/index.html';
        $config['first_url'] = base_url() . 'siswa/t_buku/index.html';

        $count_parameter = 0;

        
        /*
        if ($q <> '') {
            $config['base_url'] = base_url() . 't_buku/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 't_buku/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 't_buku/index.html';
            $config['first_url'] = base_url() . 't_buku/index.html';
        }
        */

        if (trim($judul_buku)<>"") {
            $count_parameter = $count_parameter + 1;
            $tanda = ($count_parameter > 1) ? '&' : '?' ;
            $config['base_url'] = $config['base_url'].$tanda.'judul_buku='.urlencode($judul_buku);
            $config['first_url'] = $config['base_url'].$tanda.'judul_buku='.urlencode($judul_buku);
        } 
        if (trim($id_kategori)<>"") {
            $count_parameter = $count_parameter + 1;
            $tanda = ($count_parameter > 1) ? '&' : '?' ;
            $config['base_url'] = $config['base_url'].$tanda.'id_kategori='.urlencode($id_kategori);
            $config['first_url'] = $config['base_url'].$tanda.'id_kategori='.urlencode($id_kategori);
        }
        if (trim($id_rak)<>"") {
            $count_parameter = $count_parameter + 1;
            $tanda = ($count_parameter > 1) ? '&' : '?' ;
            $config['base_url'] = $config['base_url'].$tanda.'id_rak='.urlencode($id_rak);
            $config['first_url'] = $config['base_url'].$tanda.'id_rak='.urlencode($id_rak);
        } 
        if (trim($tahun)<>"") {
            $count_parameter = $count_parameter + 1;
            $tanda = ($count_parameter > 1) ? '&' : '?' ;
            $config['base_url'] = $config['base_url'].$tanda.'tahun='.urlencode($tahun);
            $config['first_url'] = $config['base_url'].$tanda.'tahun='.urlencode($tahun);
        }


        /*
        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->T_buku_model->total_rows($q);
        $t_buku = $this->T_buku_model->get_limit_data($config['per_page'], $start, $q);
        */

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->T_buku_model->total_rows($judul_buku, $id_kategori, $id_rak, $tahun);
        $t_buku = $this->T_buku_model->get_limit_data($config['per_page'], $start, $judul_buku, $id_kategori, $id_rak, $tahun);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            't_buku_data' => $t_buku,
            'judul_buku' => $judul_buku,
            'id_kategori' => $id_kategori,
            'id_rak' => $id_rak,
            'tahun' => $tahun,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'data_kategori' => $this->T_buku_model->get_all_kategori(),
            'data_rak' => $this->T_buku_model->get_all_rak(),
        );
        $this->load->view('siswa/header');
        $this->load->view('siswa/t_buku/t_buku_list', $data);
        $this->load->view('siswa/footer');
    }
}

/* End of file T_buku.php */
/* Location: ./application/controllers/T_buku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-31 04:23:05 */
/* http://harviacode.com */