<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pilih_buku_model extends CI_Model
{

    public $table = 't_peminjaman';
    public $view = 'v_buku';
    //public $id = 'id_';
    public $order_by = 'judul_buku';
    public $order = 'ASC';
    
    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->order_by, $this->order);
        return $this->db->get($this->view)->result();
    }

    // get data by id
    /*
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->view)->row();
    }
    */
    
    // get total rows
    function total_rows($judul_buku = NULL, $id_kategori = NULL, $id_rak = NULL, $tahun = NULL) {
        /*
        $this->db->like('id_buku', $q);
        $this->db->or_like('judul_buku', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('id_rak', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('stok', $q);
        $this->db->or_like('eksemplar', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
        */

        if(trim($judul_buku)<>""){
            $where =  "(`judul_buku` LIKE '%".$judul_buku."%')";
            $this->db->where($where);
        }
        if(trim($id_kategori)<>""){
            $this->db->where("id_kategori", $id_kategori);  
        }
        if(trim($id_rak)<>""){
            $this->db->where("id_rak", $id_rak);  
        }
        if(trim($tahun)<>""){
            $this->db->where("tahun", $tahun);
        }            
        
        $this->db->from($this->view);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $judul_buku = NULL, $id_kategori = NULL, $id_rak = NULL, $tahun = NULL) {
        /*
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_buku', $q);
        $this->db->or_like('judul_buku', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('id_rak', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('stok', $q);
        $this->db->or_like('eksemplar', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
        */
        $this->db->order_by($this->order_by, $this->order);
        if(trim($judul_buku)<>""){
            $where =  "(`judul_buku` LIKE '%".$judul_buku."%')";
            $this->db->where($where);
        }
        if(trim($id_kategori)<>""){
            $this->db->where("id_kategori", $id_kategori);  
        }
        if(trim($id_rak)<>""){
            $this->db->where("id_rak", $id_rak);  
        }
        if(trim($tahun)<>""){
            $this->db->where("tahun", $tahun);
        }     
        $this->db->limit($limit, $start);
        return $this->db->get($this->view)->result();       

    }

    function get_all_kategori()
    {
        $this->db->order_by('nama_kategori');
        return $this->db->get('t_kategori')->result();
    }

    function get_all_rak()
    {
        $this->db->order_by('nama_rak');
        return $this->db->get('t_rak')->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

}

/* End of file T_buku_model.php */
/* Location: ./application/models/T_buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-31 04:23:05 */
/* http://harviacode.com */